//go:build e2e

package static_test

import (
	"fmt"
	"testing"
	"time"

	_ "github.com/go-sql-driver/mysql"

	"github.com/azerothcore/AzerothGhost/e2e/e2eharness"
)

const (
	ClassStormbringer uint8 = 16

	AbilityShock           uint32 = 804020 // generates 20 Static once Call Lightning is known
	AbilityCallLightning   uint32 = 500040 // depletes 50 Static
	AbilityConjureStorm    uint32 = 800227 // depletes 50 Static, ground targeted
	AuraStatic             uint32 = 803102 // one stack per Static point
	AuraAtLeast50Static    uint32 = 707050 // caster aura required by the 50-Static spenders
	targetLevel                   = 10
	staticWaitTimeout             = 3 * time.Second
	globalCooldown                = 1600 * time.Millisecond
	shockAttempts                 = 4
	outOfCombatObservation        = 15 * time.Second
)

// Static must be generated by Shock, depleted by Call Lightning and Conjure Storm,
// and fizzle out while out of combat.
// Main project issues: #103 (no generation), #150 (Call Lightning does not deplete,
// no decay out of combat) and #277 (Conjure Storm does not deplete).
//
//	go test -tags=e2e ./e2e/classes/stormbringer/static -run TestStormbringer_Static -count=1 -v
func TestStormbringer_Static(t *testing.T) {
	bot := e2eharness.NewSolo(t, e2eharness.ScenarioOpts{
		Prefix: "Storm",
		Race:   e2eharness.RaceOrc,
		Class:  ClassStormbringer,
		Level:  10,
	})
	bot.TeleportPad(t, e2eharness.PackagePad(t))
	for _, spell := range []uint32{AbilityShock, AbilityCallLightning, AbilityConjureStorm} {
		bot.Learn(t, spell)
	}

	dummy := bot.Spawn(t, e2eharness.CreatureHeroicTrainingDummy, 10*time.Second)
	_ = bot.World.SetTarget(dummy)
	bot.GM(t, fmt.Sprintf(".npc set level %d", targetLevel)) // a level 83 dummy resists level 10 spells
	bot.CombatReady(t)
	bot.Face(t, dummy)

	// A Shock that misses or is resisted generates nothing, so retry a few casts before
	// concluding that generation is broken; a hit must grant exactly 20 Static.
	shock := func() {
		t.Helper()
		before := bot.AuraStacks(AuraStatic)
		for attempt := 1; attempt <= shockAttempts; attempt++ {
			bot.CastMust(t, AbilityShock, dummy, 5*time.Second)
			hit := waitStacks(bot, AuraStatic, before+20)
			time.Sleep(globalCooldown)
			if hit {
				return
			}
			if got := bot.AuraStacks(AuraStatic); got != before {
				t.Errorf("E2E_FAIL: Static went from %d to %d after Shock, want +20 (#103)", before, got)
				return
			}
			t.Logf("Shock %d generated no Static (miss or resist?), retrying", attempt)
		}
		t.Errorf("E2E_FAIL: %d Shock casts generated no Static (#103)", shockAttempts)
	}

	// #103: Shock generates Static.
	for i := 0; i < 3; i++ {
		shock()
	}
	if t.Failed() {
		t.Fatalf("Static generation is broken; the spender checks need at least 50 Static (auras=%v)",
			bot.World.SelfAuras())
	}

	// #150: Call Lightning depletes 50 Static.
	bot.WaitAura(t, AuraAtLeast50Static, staticWaitTimeout)
	before := bot.AuraStacks(AuraStatic)
	bot.CastMust(t, AbilityCallLightning, dummy, 5*time.Second)
	if !waitStacks(bot, AuraStatic, before-50) {
		t.Errorf("E2E_FAIL: Static is %d after Call Lightning, want %d (#150)", bot.AuraStacks(AuraStatic), before-50)
	}
	time.Sleep(globalCooldown)

	// #277: Conjure Storm depletes 50 Static.
	for bot.AuraStacks(AuraStatic) < 50 {
		shock()
	}
	bot.WaitAura(t, AuraAtLeast50Static, staticWaitTimeout)
	before = bot.AuraStacks(AuraStatic)
	x, y, z, _ := bot.Pos()
	if res := bot.CastAtPosition(t, AbilityConjureStorm, x, y, z, 5*time.Second); !res.Success {
		t.Errorf("E2E_FAIL: Conjure Storm failed: %s", e2eharness.SpellFailReasonName(res.FailReason))
	} else if !waitStacks(bot, AuraStatic, before-50) {
		t.Errorf("E2E_FAIL: Static is %d after Conjure Storm, want %d (#277)", bot.AuraStacks(AuraStatic), before-50)
	}

}

func waitStacks(bot *e2eharness.ScenarioBot, spellID uint32, want int) bool {
	deadline := time.Now().Add(staticWaitTimeout)
	for bot.AuraStacks(spellID) != want {
		if time.Now().After(deadline) {
			return false
		}
		time.Sleep(20 * time.Millisecond)
	}
	return true
}
