//go:build e2e

package felfury_test

import (
	"fmt"
	"testing"
	"time"

	_ "github.com/go-sql-driver/mysql"

	"github.com/azerothcore/AzerothGhost/e2e/e2eharness"
)

const (
	// Fel Fireball rank 2 (2 s cast) is the rank a level 10 Felsworn owns; casting rank 1
	// (801312) instead gets no server answer at all, which reads as a harness timeout.
	AbilityFelFireballRank2 uint32 = 501281
	felfuryMaxStacks               = 6  // Felfury aura StackAmount in Spell.dbc
	dummyLevel                     = 12 // a level 83 dummy resists a level 10 caster
	generatorAttempts              = 8

	// Inner Demon now shares recovery category 133 with the rest of the class, so a second
	// cast has to wait out the 1000 ms global cooldown the first one starts.
	globalCooldown = 1100 * time.Millisecond
)

// Inner Demon must consume every Felfury point in situations the first regression test does not
// cover: a full six-point pool, points generated by a real ability instead of `.aura`, a recast
// while Inner Demon is already up, the reporter's own level, and a cast started while another
// cast is in progress. The last one is the case that broke in main project issues #245/#289:
// Inner Demon carries SPELL_ATTR4_ALLOW_CAST_WHILE_CASTING, and the core marks such casts as
// triggered, which is why the Felsworn hooks used to skip them (#391 re-reports the same symptom).
//
//	go test -tags=e2e ./e2e/classes/felsworn/felfury -run TestFelsworn_InnerDemonConsumesFelfuryVariants -count=1 -v
func TestFelsworn_InnerDemonConsumesFelfuryVariants(t *testing.T) {
	t.Run("full pool of six", func(t *testing.T) {
		bot := newFelsworn(t, "FelsSix", 10)
		grantFelfury(t, bot, felfuryMaxStacks)

		bot.CastMust(t, AbilityInnerDemon, 0, 5*time.Second)
		bot.WaitAura(t, AbilityInnerDemon, 3*time.Second)
		assertFelfurySpent(t, bot, felfuryMaxStacks)
		if got, want := bot.AuraMaxDuration(AbilityInnerDemon), felfuryMaxStacks*5*time.Second; got != want {
			t.Errorf("E2E_FAIL: Inner Demon lasts %v after consuming %d Felfury, want %v", got, felfuryMaxStacks, want)
		}
	})

	t.Run("felfury generated by Fel Fireball", func(t *testing.T) {
		bot := newFelsworn(t, "FelsGen", 10)
		bot.Learn(t, AbilityFelFireballRank2)
		dummy := bot.Spawn(t, e2eharness.CreatureHeroicTrainingDummy, 10*time.Second)
		_ = bot.World.SetTarget(dummy)
		bot.GM(t, fmt.Sprintf(".npc set level %d", dummyLevel))
		bot.CombatReady(t)
		bot.Face(t, dummy)

		// Casts miss and resist, so retry before concluding that generation is broken.
		generated := 0
		for attempt := 1; attempt <= generatorAttempts && generated == 0; attempt++ {
			bot.CastMust(t, AbilityFelFireballRank2, dummy, 6*time.Second)
			deadline := time.Now().Add(2 * time.Second)
			for time.Now().Before(deadline) && bot.AuraStacks(AuraFelfury) == 0 {
				time.Sleep(20 * time.Millisecond)
			}
			generated = bot.AuraStacks(AuraFelfury)
			if generated == 0 {
				t.Logf("Fel Fireball %d generated no Felfury (miss or resist?), retrying", attempt)
			}
		}
		if generated == 0 {
			t.Fatalf("%d Fel Fireball casts generated no Felfury; cannot test consumption of generated points", generatorAttempts)
		}
		t.Logf("Fel Fireball generated %d Felfury", generated)

		bot.CastMust(t, AbilityInnerDemon, 0, 5*time.Second)
		bot.WaitAura(t, AbilityInnerDemon, 3*time.Second)
		assertFelfurySpent(t, bot, generated)
	})

	t.Run("recast while Inner Demon is up", func(t *testing.T) {
		bot := newFelsworn(t, "FelsRe", 10)
		grantFelfury(t, bot, 3)
		bot.CastMust(t, AbilityInnerDemon, 0, 5*time.Second)
		bot.WaitAura(t, AbilityInnerDemon, 3*time.Second)
		assertFelfurySpent(t, bot, 3)

		time.Sleep(globalCooldown)
		grantFelfury(t, bot, 2)
		bot.CastMust(t, AbilityInnerDemon, 0, 5*time.Second)
		assertFelfurySpent(t, bot, 2)
	})

	t.Run("at the reported level 4", func(t *testing.T) {
		bot := newFelsworn(t, "FelsLow", 4)
		grantFelfury(t, bot, 2)
		bot.CastMust(t, AbilityInnerDemon, 0, 5*time.Second)
		bot.WaitAura(t, AbilityInnerDemon, 3*time.Second)
		assertFelfurySpent(t, bot, 2)
	})

	t.Run("cast while another cast is in progress", func(t *testing.T) {
		bot := newFelsworn(t, "FelsC", 10)
		bot.Learn(t, AbilityFelFireballRank2)
		// `.aura` applies to the current selection, so grant Felfury before targeting the dummy.
		grantFelfury(t, bot, 3)
		dummy := bot.Spawn(t, e2eharness.CreatureHeroicTrainingDummy, 10*time.Second)
		_ = bot.World.SetTarget(dummy)
		bot.GM(t, fmt.Sprintf(".npc set level %d", dummyLevel))
		bot.CombatReady(t)
		bot.Face(t, dummy)

		// Start the 2 s Fel Fireball without waiting for its result, wait out the global cooldown
		// it starts, then cast Inner Demon while that cast is still running. Cast both through the
		// session directly: TryCast re-arms the waiter and would drop the Fel Fireball result.
		bot.ArmSpellWaiter()
		if err := bot.World.CastSpell(AbilityFelFireballRank2, dummy); err != nil {
			t.Fatalf("start Fel Fireball: %v", err)
		}
		time.Sleep(globalCooldown)
		if err := bot.World.CastSpell(AbilityInnerDemon, 0); err != nil {
			t.Fatalf("cast Inner Demon during Fel Fireball: %v", err)
		}
		res, err := bot.WaitSpellID(AbilityInnerDemon, 3*time.Second)
		if err != nil {
			t.Fatalf("wait for Inner Demon result: %v", err)
		}
		if !res.Success {
			t.Fatalf("Inner Demon refused during another cast (%s); the variant cannot be measured",
				e2eharness.SpellFailReasonName(res.FailReason))
		}
		bot.WaitAura(t, AbilityInnerDemon, 3*time.Second)
		// Check the pool before Fel Fireball lands: its hit generates a fresh Felfury point.
		assertFelfurySpent(t, bot, 3)
		// The interrupted-cast case would never reach SPELL_GO, so this also shows that
		// Inner Demon did not cancel the spell that was already being cast.
		if _, err := bot.WaitSpellID(AbilityFelFireballRank2, 3*time.Second); err != nil {
			t.Errorf("E2E_FAIL: Fel Fireball never completed after Inner Demon was cast during it: %v", err)
		}
	})
}

func newFelsworn(t *testing.T, prefix string, level int) *e2eharness.ScenarioBot {
	t.Helper()
	bot := e2eharness.NewSolo(t, e2eharness.ScenarioOpts{
		Prefix: prefix,
		Race:   e2eharness.RaceOrc,
		Class:  ClassFelsworn,
		Level:  level,
	})
	bot.TeleportPad(t, e2eharness.PackagePad(t))
	bot.Learn(t, AbilityInnerDemon)
	return bot
}

// grantFelfury adds stacks points one `.aura` at a time; each application adds one stack.
func grantFelfury(t *testing.T, bot *e2eharness.ScenarioBot, stacks int) {
	t.Helper()
	have := bot.AuraStacks(AuraFelfury)
	for want := have + 1; want <= have+stacks; want++ {
		bot.GM(t, fmt.Sprintf(".aura %d", AuraFelfury))
		waitStacks(t, bot, AuraFelfury, want)
	}
}

func assertFelfurySpent(t *testing.T, bot *e2eharness.ScenarioBot, had int) {
	t.Helper()
	if !bot.TryWaitAuraGone(t, AuraFelfury, 2*time.Second) {
		t.Errorf("E2E_FAIL: Felfury still has %d stack(s) after Inner Demon consumed %d, want 0 (#391)",
			bot.AuraStacks(AuraFelfury), had)
		return
	}
	t.Logf("E2E_PASS: Inner Demon consumed %d Felfury", had)
}
