//go:build e2e

package rage_test

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"sync/atomic"
	"testing"
	"time"

	_ "github.com/go-sql-driver/mysql"

	"github.com/azerothcore/AzerothGhost/client"
	"github.com/azerothcore/AzerothGhost/e2e/e2eharness"
)

const (
	ClassWitchHunter uint8 = 15
	ClassPrimalist   uint8 = 31

	powerRage         uint8 = 1
	botLevel                = 10
	meleeWindow             = 12 * time.Second
	engageTimeout           = 15 * time.Second
	dummySpawnTimeout       = 10 * time.Second
)

// Witch Hunters and Primalists use Mana as their primary power and Rage as a
// secondary one. Their talents describe Rage generated by auto attacks and damage
// dealt, so melee swings must build Rage.
// Main project issues: #213 (Witch Hunter) and #110 (Primalist).
//
//	go test -tags=e2e ./e2e/coa/rage -count=1 -v
func TestCoA_MeleeGeneratesRage(t *testing.T) {
	for _, c := range []struct {
		name   string
		prefix string
		class  uint8
		issue  int
	}{
		// Control: a Warrior has Rage as primary power and must pass on any working setup.
		{"WarriorControl", "WaRage", e2eharness.ClassWarrior, 0},
		{"WitchHunter", "WHRage", ClassWitchHunter, 213},
		{"Primalist", "PrRage", ClassPrimalist, 110},
	} {
		t.Run(c.name, func(t *testing.T) {
			bot := e2eharness.NewSolo(t, e2eharness.ScenarioOpts{
				Prefix: c.prefix,
				Race:   e2eharness.RaceOrc,
				Class:  c.class,
				Level:  botLevel,
			})
			bot.TeleportPad(t, e2eharness.PackagePad(t))

			dummy := bot.Spawn(t, e2eharness.CreatureHeroicTrainingDummy, dummySpawnTimeout)
			_ = bot.World.SetTarget(dummy)
			bot.GM(t, fmt.Sprintf(".npc set level %d", botLevel)) // a level 83 dummy parries and dodges most swings

			var maxRage atomic.Uint32
			defer trackPower(bot, powerRage, &maxRage)()

			bot.CombatReady(t)
			bot.Face(t, dummy)
			bot.Engage(t, dummy, engageTimeout)
			bot.Attack(t, dummy)
			time.Sleep(meleeWindow)
			bot.CombatStop(t)

			if got := maxRage.Load(); got == 0 {
				t.Errorf("E2E_FAIL: no Rage after %v of melee swings (#%d)", meleeWindow, c.issue)
			} else {
				t.Logf("E2E_PASS: melee swings raised Rage to %d (internal tenths)", got)
			}
		})
	}
}

// trackPower records the highest value of powerType sent to the player in SMSG_POWER_UPDATE.
func trackPower(bot *e2eharness.ScenarioBot, powerType uint8, highest *atomic.Uint32) (cancel func()) {
	self := bot.World.CharGUID()
	return bot.World.AddPacketHook(func(opcode uint16, data []byte) {
		if opcode != client.SmsgPowerUpdate {
			return
		}
		r := bytes.NewReader(data)
		mask, err := r.ReadByte()
		if err != nil {
			return
		}
		var guid uint64
		for i := uint8(0); i < 8; i++ {
			if mask&(1<<i) != 0 {
				b, err := r.ReadByte()
				if err != nil {
					return
				}
				guid |= uint64(b) << (i * 8)
			}
		}
		var power uint8
		var value uint32
		if guid != self || binary.Read(r, binary.LittleEndian, &power) != nil ||
			binary.Read(r, binary.LittleEndian, &value) != nil || power != powerType {
			return
		}
		for {
			old := highest.Load()
			if value <= old || highest.CompareAndSwap(old, value) {
				return
			}
		}
	})
}
